// Code generated by Slice Machine. DO NOT EDIT.

import CollectionSlider from './CollectionSlider/index.svelte';
import HeroImageWithText from './HeroImageWithText/index.svelte';
import HeroSlider from './HeroSlider/index.svelte';
import ImageDescription from './ImageDescription/index.svelte';
import NonPrismicContent from './NonPrismicContent/index.svelte';

export const components = {
	collection_slider: CollectionSlider,
	hero_image_with_text: HeroImageWithText,
	hero_slider: HeroSlider,
	image_description: ImageDescription,
	non_prismic_content: NonPrismicContent
};
