// Code generated by Slice Machine. DO NOT EDIT.

import CollectionSlider from './CollectionSlider/index.svelte';
import HeroSlider from './HeroSlider/index.svelte';
import ImageDescription from './ImageDescription/index.svelte';

export const components = {
	hero_slider: HeroSlider,
	image_description: ImageDescription,
	collection_slider: CollectionSlider
};
